FROM ubuntu:latest

MAINTAINER Pedro Fernandez <pedro.fernandez@koombea.com>

RUN sudo apt-get update

RUN sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties

RUN sudo apt-get install -y -qt4-dev-tools libqt4-dev libqt4-core libqt4-gui
RUN sudo apt-get install -y imagemagick libmagickwand-dev
